# Generated by Django 6.0.4 on 2026-04-22 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TireAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analyses/%Y/%m/%d/')),
                ('condition', models.CharField(choices=[('good', 'Baik'), ('worn', 'Aus'), ('damaged', 'Rusak'), ('unknown', 'Tidak Diketahui'), ('not_tire', 'Bukan Ban')], default='unknown', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('tire_year', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_mode', models.CharField(choices=[('front', 'Depan'), ('rear', 'Belakang')], default='front', max_length=10)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisis Ban',
                'verbose_name_plural': 'Analisis Ban',
                'ordering': ['-created_at'],
            },
        ),
    ]
